version: 1.0.{build}
image:
  - Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: nuget pack src\Innofactor.Xrm.Json.Serialization\Innofactor.Xrm.Json.Serialization.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: plVZVEG/g8+AKx8nujq5O2I7zbAXSnZBnL/kQXA4aJ+5NOqCEkdWvSj3zvUsgxtU