version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: dir src\Innofactor.Xrm.Json.Serialization\bin\Release\ && nuget pack src\Innofactor.Xrm.Json.Serialization\Innofactor.Xrm.Json.Serialization.csproj -Version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'